### ISSUE TITLE
Signup fails to save user 

### ISSUE THREAD

**Issue by kchapple** [LibreHealthIO/ehr-fhir-api#29]
To reproduce:

Try to signup with an email,  but missing other required field to cause failure.

Fix user input error and POST to signup again. 

Expected: Signup succes.

Actual: Signup error saying email is already taken. 
{"accountRegistered":0,"status":"FAIL","message":"Fail to save user","Errors":{"email":["The email has already been taken."]}}

**Comment by Leo24** [comment]
https://github.com/LibreEHR/fhir/pull/31

Add validation rule for mobile number
to prevent Signup error saying email is already taken
