### ISSUE TITLE
Attempt to access unauthorized endpoint throws exception

### ISSUE THREAD

**Issue by kchapple** [LibreHealthIO/ehr-fhir-api#33]
To reproduce, browse to https://gponline-fhir.vu2vu.com/fhir/Appointment?patient=1 without siging in.

Expected: Response should be an OperationOutcome with a 401 Unauthorized and potentially OperationOutcome error message.

Actual: redirect to /login route and get exception
![screen shot 2016-09-22 at 9 46 00 am](https://cloud.githubusercontent.com/assets/271809/18750801/a66f0b4e-80aa-11e6-9394-ca0cf567c7c0.png)

**Comment by Leo24** [comment]
To get response
{
  "error": "Unauthenticated."
}
set your headers using Postman
Accept header to application/json 
Content-Type header to  application/json
http://storage6.static.itmages.com/i/16/0926/h_1474890624_3476390_568cdab974.png
Also added response for login route on Unauthorised request in browser
https://github.com/LibreEHR/fhir/pull/41
