### ISSUE TITLE
Get [base]/Appointment Should return all Appointments

### ISSUE THREAD

**Issue by kchapple** [LibreHealthIO/ehr-fhir-api#34]
To reproduce, first authenticate, then browse to https://gponline-fhir.vu2vu.com/fhir/Appointment

Expected: retrieve list of all appointments if authorized, 401 otherwise

Actual: Exception 
![screen shot 2016-09-22 at 10 00 46 am](https://cloud.githubusercontent.com/assets/271809/18751078/aa38d72c-80ab-11e6-9330-4d6cc0d9089f.png)

**Comment by Leo24** [comment]
Add functionality to return all Appointments if no query params provided
https://github.com/LibreEHR/fhir/pull/42
