### ISSUE TITLE
Add Patient Extensions for GPOnline

### ISSUE THREAD

**Issue by kchapple** [LibreHealthIO/ehr-fhir-api#39]
Add patient extensions for GPOnline sollowing the Google Doc "View your Appointment - Endpoint Mockup Data"

`"extension" : [
         {
           "url" : "[base]/extensions/gponline-patient-data",
           "extension" : [
            {
             "url" : "#groupId",
              "valueString" : "1001"
             },
             {
               "url" : "#status",
               "valueString" : "pending"
             },
             {
               "url" : "#providerId",
               "valueString" : "34"
             },
             {
               "url" : "#pharmacyId",
               "valueString" : "5"
             },
             {
               "url" : "#stripeToken",
               "valueString" : "some-value"
             }
           ]
         }
       ]`

**Comment by Leo24** [comment]
Added patient extensions for GPOnline
https://github.com/LibreEHR/fhir/pull/45
