### ISSUE TITLE
FHIRPatientAdapter needs Address mapped

### ISSUE THREAD

**Issue by kchapple** [LibreHealthIO/ehr-fhir-api#60]
modelToInterface() and interfaceToModel() need to map address fields to and from LibreEHR.

Here are the mappings from FHIR on left, LibreEHR patient_data table on right:

line => street (separate lines by "|" character on input and output)
city => city
district => county

`{
 "resourceType": "Patient",
  "name": [
   {
     "use": "usual",
     "family": [
       "Everywoman3"
     ],
     "given": [
       "Judy Simple"
     ]
   }
 ],
 "telecom": [
   {
     "system": "phone",
     "value": "555-555-2003",
     "use": "primary"
   },
   {
     "system": "email",
     "value": "",
     "use": "primary"
   }
 ],
 "gender": "female",
 "birthDate": "1955-01-06",
 "address": [
   {
     "use": "home",
     "line": [
       "45 pine st",
       "Mt eden"
     ],
     "city": "Auckland",
     "district" : "Cork"
   }
 ],
 "extension": [
   {
     "url": "https://gponline-fhir.vu2vu.com/extension/gponline-patient-data",
     "extension": [
       {
         "url": "#groupId",
         "valueString": ""
       },
       {
         "url": "#status",
         "valueString": "pending"
       },
       {
         "url": "#providerId",
         "valueString": "1"
       },
       {
         "url": "#pharmacyId",
         "valueString": "2"
       },
       {
         "url": "#stripeToken",
         "valueString": "some-value"
       }
     ]
   }
 ]
}`

**Comment by Leo24** [comment]
Add Address info to FHIRPatientAdapter
https://github.com/LibreEHR/core/pull/22
https://github.com/LibreEHR/fhir/pull/63
