### ISSUE TITLE
Some appointment fileds are not being populated including start date, recurspec , etc

### ISSUE THREAD

**Issue by kchapple** [LibreHealthIO/ehr-fhir-api#61]
See the differences in this dump of 32, which is an appointment created through API, and 30, which is an appointment created in LibreEHR. The duration is off (should follow the admin > globals >calendar settings) and the pc_time, pc_eventDate and recurspec stick out to me as being important.

`$libreehr_postcalendar_events = array(
  array('pc_eid' => '32','pc_catid' => '0','pc_multiple' => '0','pc_aid' => '1','pc_pid' => '1','pc_title' => NULL,'pc_time' => NULL,'pc_hometext' => 'XCXCXC XCXCXCXCXC','pc_comments' => '0','pc_counter' => '0','pc_topic' => '1','pc_informant' => NULL,'pc_eventDate' => '0000-00-00','pc_endDate' => '0000-00-00','pc_duration' => '333333','pc_recurrtype' => '0','pc_recurrspec' => NULL,'pc_recurrfreq' => '0','pc_startTime' => '01:44:19','pc_endTime' => '13:17:39','pc_alldayevent' => '0','pc_location' => '{"portalUri":"openemr.test.vu2vu.com","roomKey":"h0TmZnpwq0UY0NcnrAAIcX9A60","pin":"5624"}','pc_conttel' => NULL,'pc_contname' => NULL,'pc_contemail' => NULL,'pc_website' => NULL,'pc_fee' => NULL,'pc_eventstatus' => '0','pc_sharing' => '0','pc_language' => NULL,'pc_apptstatus' => '=','pc_prefcatid' => '0','pc_facility' => '0','pc_sendalertsms' => 'NO','pc_sendalertemail' => 'NO','pc_billing_location' => '0','pc_room' => ''),
  array('pc_eid' => '30','pc_catid' => '5','pc_multiple' => '0','pc_aid' => '1','pc_pid' => '1','pc_title' => 'Office Visit','pc_time' => '2016-09-20 15:28:19','pc_hometext' => '','pc_comments' => '0','pc_counter' => '0','pc_topic' => '1','pc_informant' => '1','pc_eventDate' => '2016-09-20','pc_endDate' => '0000-00-00','pc_duration' => '900','pc_recurrtype' => '0','pc_recurrspec' => 'a:6:{s:17:"event_repeat_freq";s:1:"0";s:22:"event_repeat_freq_type";s:1:"0";s:19:"event_repeat_on_num";s:1:"1";s:19:"event_repeat_on_day";s:1:"0";s:20:"event_repeat_on_freq";s:1:"0";s:6:"exdate";s:0:"";}','pc_recurrfreq' => '0','pc_startTime' => '16:00:00','pc_endTime' => '16:15:00','pc_alldayevent' => '0','pc_location' => '{"portalUri":"http:\\/\\/openemr.test.vu2vu.com","roomKey":"TsrK98VF5xWFfGE9Al2CRd0IIfg","pin":4425}','pc_conttel' => NULL,'pc_contname' => NULL,'pc_contemail' => NULL,'pc_website' => NULL,'pc_fee' => NULL,'pc_eventstatus' => '1','pc_sharing' => '1','pc_language' => NULL,'pc_apptstatus' => '@','pc_prefcatid' => '0','pc_facility' => '3','pc_sendalertsms' => 'NO','pc_sendalertemail' => 'NO','pc_billing_location' => '3','pc_room' => ''),
);`

**Comment by Leo24** [comment]
Add functionality to enable showing API Appointments in calendar
https://github.com/LibreEHR/fhir/pull/67
https://github.com/LibreEHR/core/pull/24
