### ISSUE TITLE
Appointments Resource should have "participant" array

### ISSUE THREAD

**Issue by kchapple** [LibreHealthIO/ehr-fhir-api#69]
We need to add the participants of the appointment to the participants array in the Appointment resource. 

See example Appointment Response with participants:
{
  "comment": "Further expand on the results of the MRI and determine the next actions that may be appropriate.",
  "description": "Discussion on the results of your recent MRI",
  "end": "2013-12-10T11:00:00Z",
  "id": "231",
  "participant": [
    {
      "actor": {
        "display": "Peter James Chalmers",
        "reference": "Patient/4"
      },
      "required": "required",
      "status": "accepted"
    },
    {
      "actor": {
        "display": "Dr Adam Careful",
        "reference": "Practitioner/2"
      },
      "required": "required",
      "status": "accepted"
    }
  ],
  "priority": 5,
  "resourceType": "Appointment",
  "start": "2013-12-10T09:00:00Z",
  "status": "booked",
  "text": {
    "div": "<div>Brian MRI results discussion</div>",
    "status": "generated"
  },
  "type": {
    "coding": [
      {
        "code": "52",
        "display": "General Discussion"
      }
    ]
  }
}

**Comment by Leo24** [comment]
https://github.com/LibreEHR/fhir/pull/78
Add "participants" to Appointments Resource
For patient and provider used type property because it is array and I can add there several values of participants.
For actor, in setActor method it can be added only one participant instead previous.
