### ISSUE TITLE
Add fhir/config/config.php

### ISSUE THREAD

**Issue by kchapple** [LibreHealthIO/ehr-fhir-api#79]
Please add a config file like app.php spcifically for fhir configuration, and add a class to access FHIRConfig.php like FHIRConfig::get('stripe-api-token') or whatever the Laravel convension is for config files.

Use this to store and retrieve stripe API token

**Comment by Leo24** [comment]
https://github.com/LibreEHR/fhir/pull/80
Added FHIRConfig.php to laravel config directory
https://github.com/Leo24/Libre/blob/laravel_5_3/config/FHIRConfig.php
